# Generated by Django 2.2.1 on 2019-06-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('speaker', models.CharField(max_length=100)),
                ('venue', models.TextField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
